services:
  user-management-service-db:
    image: postgres:17.4-alpine
    container_name: user-management-service-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  user-management-service-app:
    image: user-management-service:0.7
    container_name: user-management-service-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://user-management-service-db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      DB_SCHEMA: public
    depends_on:
      - user-management-service-db
    ports:
      - "8080:8080"

volumes:
  postgres_data:
